workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and get packages
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS app for simulator
        script: |
          flutter build ios --debug --simulator -t lib/main.dart
    artifacts:
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - khadijaalamoudi169@gmail.com
