import "package:flutter/material.dart";
import 'package:get_storage/get_storage.dart';
import 'package:get/get.dart' show GetMaterialApp;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:todo_app_new/core/Theme/theme.dart';
import 'package:todo_app_new/core/services/theme_services.dart';
import 'package:todo_app_new/presentation/pages/splash_page.dart';
import 'package:todo_app_new/core/services/notification_services.dart';
// Generated by `flutter gen-l10n` (runs automatically on `flutter pub get`
// since pubspec.yaml has `flutter: generate: true`) from the ARB files in
// lib/l10n/. If your IDE shows this as missing, run `flutter pub get` once.
import 'package:todo_app_new/l10n/app_localizations.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await NotifyHelper().initializeNotification();
  await GetStorage.init();
  // NOTE: DBHelper.initDb() used to be called explicitly here. The new
  // TaskLocalDataSource opens the database lazily on first query instead
  // (see task_local_data_source.dart), so no explicit init call is needed.
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // GetMaterialApp is kept intentionally: this refactor replaces GetX's
    // *state management* (TaskController -> Riverpod) but keeps GetX for
    // navigation and UI utilities (Get.to, Get.snackbar, Get.dialog,
    // Get.bottomSheet), which is a separate, independent concern.
    return GetMaterialApp(
      theme: Themes.light,
      darkTheme: Themes.dark,
      themeMode: ThemeServices().theme,
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      // Localization starter (roadmap Phase 4): infrastructure is wired up
      // and English + Arabic are provided, but only a handful of screens
      // have been converted to use AppLocalizations.of(context) so far —
      // see home_page.dart's app bar title for the pattern. Extending it
      // to every remaining hardcoded string is mechanical follow-up work.
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      home: const SplashScreen(),
    );
  }
}
